# Site settings
title:          Blog
description:    ""
path: /blog 
url:  'byteofprash.github.io/blog/'

# Author
author:
  name:         Prashanth 


# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
